### ISSUE TITLE
webapp installation  issue

### ISSUE THREAD

**Issue by Crispae** [maemresen/android-keylogger#6]
while installing the keylogwebapp i faced the issue **NoClassDefFound Could not initialize**, after deleting .m2/repo  still the issue not resolved.
java version -java 15.0.2 
Maven -3.6.3

![mvn](https://user-images.githubusercontent.com/74324530/108155234-8760ad80-7104-11eb-950f-16644200b8ba.PNG)

**Comment by Crispae** [comment]
could you explain the process of compiling the apk file regarding this ?

**Comment by maemresen** [comment]
@Crispae  Actually, I do not get an error message on my local but regarding to screenshot you share, I have noticed that there are some redundant test classes remained in repository. Thanks for feedback. 
I have cleaned them and push updates to the main branch. You may try again and share the results if the problem still exists.

About your second question, actually there is no special process for building APK for Android Application. You can just open the project in Android Studio and generate APK. You may check the following link for guidline
https://developer.android.com/studio/run

Also don't forget to read [README#Usage](https://github.com/maemresen/android-keylogger/blob/main/README.md#usage). Required steps for testing application explained on there.

**Comment by Crispae** [comment]
thanks for the update, it is working fine for me now.
